os: osx
language: node_js
node_js:
  - 'node'
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
install:
  - yarn global add codecov
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn test-cov
  - yarn build-e2e
  - yarn test-e2e
after_success:
  - codecov
