image: Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 'Current'

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn install

test_script:
  - yarn lint
  - yarn test

deploy_script:
  - yarn package-ci
