export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
export const LOAD_IMAGE_ERROR = 'LOAD_IMAGE_ERROR';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
