export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_ERROR = 'FETCH_IMAGES_ERROR';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_ERROR = 'REFRESH_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FETCH_OATH_URL = 'FETCH_OATH_URL';
export const FETCH_OATH_URL_SUCCESS = 'FETCH_OATH_URL_SUCCESS';
export const FETCH_OATH_URL_ERROR = 'FETCH_OATH_URL_ERROR';

export const AUTHORIZE = 'AUTHORIZE';
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_ERROR = 'AUTHORIZE_ERROR';

export const FETCH_MODULES = 'FETCH_MODULES';
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS';
export const FETCH_MODULES_ERROR = 'FETCH_MODULES_ERROR';
