#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '👀 Searching for mistakes...'

# Check Prettier standards
echo '👀 Checking formatting...'
npm run format --check ||
(
    echo '❌ Prettier Check Failed. Run "npm run format --write", commit changes and try again.';
    false;
)

# Check ESLint Standards
echo '👀 Checking linting...'
npm run lint ||
(
    echo '❌ ESLibnt Check Failed. Run "npm run lint --fix", commit changes and try again.';
    false;
)

# Check tsconfig standards
echo '👀 Checking types...'
npm run type-check ||
(
    echo '❌ Type checks Failed. Make the required changes listed above, commit changes and try again.'
    false;
)

# Check tests
# TODO: Add tests
# echo '👀 Checking tests...'
# npm run test ||
# (
#     echo '❌ Tests failed. Review the failing tests above. '
#     false;
# )

# Check build
echo '👀 Checking build...'
npm run build ||
(
    echo '❌ Build failed: Review the errors above.'
    false;
)

# If everything passes... Now we can push
echo '✅ You win this time...'
